<a href="https://colab.research.google.com/github/Gurubux/MLZoomcamp/blob/main/MLZoompcamp_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-11 12:30:52--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.2’

data.csv.2          100%[===================>]   1.41M  --.-KB/s    in 0.03s   

2022-09-11 12:30:53 (41.8 MB/s) - ‘data.csv.2’ saved [1475504/1475504]



# Question 1: Version of NumPy

In [105]:
import numpy as np
np.__version__

'1.21.6'

# Question 2: Number of records in the dataset

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/data.csv')

In [ ]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [ ]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

# Question 3: The most popular car manufacturers

In [ ]:
df[['Make','Popularity']].drop_duplicates().sort_values('Popularity',ascending=True)

Make  Popularity
2116          Spyker           2
5202         Genesis          21
1287      Oldsmobile          26
1650         Lincoln          61
611          Maybach          67
2921     Rolls-Royce          86
4893           Scion         105
474       Alfa Romeo         113
5692          HUMMER         130
2341           Buick         155
4269        Infiniti         190
2696           Acura         204
674          Pontiac         210
3030        Maserati         238
3551      Land Rover         258
3520    Aston Martin         259
800             Saab         376
604          McLaren         416
194       Mitsubishi         436
3173           Lexus         454
1300          Suzuki         481
1452         Bentley         520
1189        Plymouth         535
1137             GMC         549
112            Mazda         586
3912           Lotus         613
35     Mercedes-Benz         617
1747          Subaru         640
32              FIAT         819
11362        Bugatti         820
104            Volvo         870
1792      Volkswagen         873
64          Chrysler        1013
1620     Lamborghini        1158
1476       Chevrolet        1385
6921           Tesla        1391
1171         Hyundai        1439
1367        Cadillac        1624
736          Porsche        1715
1426             Kia        1720
1610           Dodge        1851
87            Nissan        2009
479           Toyota        2031
1192           Honda        2202
294          Ferrari        2774
17              Audi        3105
0                BMW        3916
1331            Ford        5657

In [ ]:
df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

# Question 4: Number of unique Audi car models

In [ ]:
df[df['Make']=='Audi']['Model'].nunique()

34

# Question 5: Number of columns with missing values

In [ ]:
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

# Question 6: Does the median value change after filling missing values?

In [ ]:
df['Engine Cylinders'].median()

6.0

In [ ]:
df['Engine Cylinders'].mode().values[0]

4.0

In [ ]:
df['Engine Cylinders']=df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode().values[0])

In [ ]:
df['Engine Cylinders'].median()

6.0

# Questions 7: Value of the first element of w

In [ ]:
X = df[df['Make']=='Lotus'][["Engine HP", "Engine Cylinders"]].drop_duplicates().to_numpy()

In [ ]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [ ]:
XTX = X.T.dot(X)

In [ ]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [ ]:
XTX_inv = np.linalg.inv(XTX)

In [ ]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [ ]:
w=(XTX_inv.dot(X.T)).dot(y)

In [ ]:
w

array([  4.59494481, -63.56432501])